#!/bin/bash

EXISTS=${find /etc/cron.d/ | grep update}

if ! [[ /etc/cron.d/update -e ]]
then
	echo "0 4 * * 1 /home/modnosum/update_script.bash"
fi

apt-get update > /var/log/update_script.log
apt-get upgrade >> /var/log/update_script.log
